FROM builder

ARG MAX_JOBS=2
ARG NVCC_THREADS=4

# Build latest SageAttention
RUN --mount=type=cache,target=/cache/uv,sharing=locked \
    . venv/bin/activate && \
    uv pip install ninja wheel packaging && \
    git clone https://github.com/woct0rdho/SageAttention.git && \
    export TORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0 12.0" && \
    export SAGEATTENTION_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST} && \
    cd SageAttention && \
    uv build --wheel
