FROM builder

ARG MAX_JOBS=2
ARG NVCC_THREADS=4

# Build latest xformers
RUN --mount=type=cache,target=/cache/uv,sharing=locked \
    . venv/bin/activate && \
    git clone https://github.com/facebookresearch/xformers.git && \
    export TORCH_CUDA_ARCH_LIST="7.5 8.0 8.6 8.9 9.0 12.0" && \
    cd xformers && \
    git submodule update --init --recursive && \
    uv build --wheel
