name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: comfyui

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pre-create BuildKit volume on /mnt
        run: |
          sudo mkdir -p /mnt/buildkit-state

      - name: Create builder
        run: |
          docker buildx create \
            --name ci \
            --driver docker-container \
            --buildkitd-flags '--config /etc/buildkit/buildkitd.toml' \
            --driver-opt env.BUILDKITD_FLAGS="--config=/etc/buildkit/buildkitd.toml" \
            --driver-opt "mount=type=bind,src=$PWD/.github/buildkitd.toml,target=/etc/buildkit/buildkitd.toml,readonly=true" \
            --driver-opt "mount=type=bind,src=/mnt/buildkit,target=/mnt/buildkit" \
            --use --bootstrap

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        env:
          DOCKER_REGISTRY_URL: ${{ env.REGISTRY }}/${{ github.repository_owner }}/
          PUSH_FLAG: ${{ github.event_name != 'pull_request' && '--push' || '' }}
        run: |
          docker buildx bake $PUSH_FLAG \
          --set '*.cache-from=type=gha,scope=comfyui-cache' \
          --set '*.cache-to=type=gha,mode=max,scope=comfyui-cache,github.token=${{ secrets.GITHUB_TOKEN }}'
