name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: comfyui

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        env:
          DOCKER_REGISTRY_URL: ${{ env.REGISTRY }}/${{ github.repository_owner }}/
          PUSH_FLAG: ${{ github.event_name != 'pull_request' && '--push' || '' }}
        run: |
          docker buildx bake comfyui-base $PUSH_FLAG
          docker buildx prune -f
          docker buildx bake comfyui-extensions $PUSH_FLAG
          docker buildx prune -f
          docker buildx bake comfyui-omnigen2 $PUSH_FLAG
