name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: comfyui

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check disk space
        run: df -h

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
          targets: |
            comfyui-base
            comfyui-extensions
            comfyui-omnigen2
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.platform=linux/amd64
            *.cache-from=type=local,src=/mnt/.buildx-cache
            *.cache-to=type=local,dest=/mnt/.buildx-cache
          allow: |
            fs=/mnt
