name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pre-create BuildKit volume on /mnt
        run: |
          sudo mkdir -p /mnt/buildkit-state
          sudo docker volume create \
            --driver local \
            --opt type=none \
            --opt device=/mnt/buildkit-state \
            --opt o=bind \
            buildx_buildkit_ci0_state

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          name: ci
          driver: docker-container
          use: true

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/bake-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          env: |
            DOCKER_REGISTRY_URL: ${{ env.REGISTRY }}/${{ github.repository_owner }}/
