name: Build and push Docker images

on:
  workflow_call:
    inputs:
      comfyui_ref:
        description: "ComfyUI branch or tag to build from"
        required: true
        type: string
      image_label:
        description: "Label to apply to the built image"
        required: true
        type: string
      bake_target:
        description: "Docker Bake target to build"
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  DOCKER_REGISTRY_URL: ghcr.io/${{ github.repository_owner }}/
  IMAGE_LABEL: ${{ inputs.image_label }}
  COMFYUI_VERSION: ${{ inputs.comfyui_ref }}

jobs:
  build-nvidia-builders:
    name: Build NVIDIA builder images
    uses: ./.github/workflows/build-nvidia.yml
    with:
      comfyui_ref: ${{ inputs.comfyui_ref }}
      image_label: ${{ inputs.image_label }}
      bake_target: ${{ inputs.bake_target }}

  build:
    needs: [build-nvidia-builders]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        base_flavor: [nvidia, cpu, amd]
    env:
      BASE_FLAVOR: ${{ matrix.base_flavor }}
    steps:
      - uses: actions/checkout@v4
      - name: Build (flavor=${{ matrix.base_flavor }})
        uses: ./.github/actions/bake-build
        with:
          comfyui_ref: ${{ inputs.comfyui_ref }}
          image_label: ${{ inputs.image_label }}
          targets: ${{ inputs.bake_target || 'default' }}
          push: ${{ github.event_name != 'pull_request' && 'true' || 'false' }}
          registry: ${{ env.REGISTRY }}
          docker_registry_url: ${{ env.DOCKER_REGISTRY_URL }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          extra_set: |
            nvidia-xformers.args.MAX_JOBS=1
            nvidia-xformers.args.NVCC_THREADS=4
            nvidia-sageattention.args.MAX_JOBS=1
            nvidia-sageattention.args.NVCC_THREADS=4
            nvidia-nunchaku.args.MAX_JOBS=1
            nvidia-nunchaku.args.NVCC_THREADS=4
            nvidia-flashattention.args.MAX_JOBS=1
            nvidia-flashattention.args.NVCC_THREADS=2
