name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCKER_REGISTRY_URL: ghcr.io/${{ github.repository_owner }}/

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pre-create BuildKit volume on /mnt
        run: |
          sudo mkdir -p /mnt/buildkit-state
          sudo docker volume create \
            --driver local \
            --opt type=none \
            --opt device=/mnt/buildkit-state \
            --opt o=bind \
            buildx_buildkit_ci0_state

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          name: ci

      - name: Create bake cache directories
        run: |
          sudo mkdir -p /mnt/bake-cache-root
          sudo chown $USER:$USER /mnt/bake-cache-root

      - name: Cache PIP packages
        uses: actions/cache@v4
        with:
          path: /mnt/bake-cache-root/pip
          key: ${{ runner.os }}-bake-cache-pip-${{ hashFiles('dockerfile.base') }}

      - name: Inject cache mount
        uses: reproducible-containers/buildkit-cache-dance@v2
        with:
          cache-source: /mnt/bake-cache-root/pip
          cache-target: /cache/pip

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/bake-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
