name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: comfyui

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      # - name: Build docker manually
      #   run: docker buildx bake comfyui-base

      - name: Build base image
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
          targets: |
            comfyui-base
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.platform=linux/amd64
            *.output=type=oci,dest=/tmp/out.tar
