name: Trigger builds on pull requests to main

on:
  pull_request:
    branches: [main]

jobs:
  build-pull-request-nvidia:
    uses: ./.github/workflows/build-nvidia.yml
    with:
      comfyui_ref: "master"
      image_label: "master"
      push_images: false
    permissions:
      contents: read
      packages: write
    secrets: inherit

  build-pull-request-base-flavors:
    strategy:
      fail-fast: false
      matrix:
        base_flavor: [cpu, amd]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-flavor.yml
    with:
      comfyui_ref: "master"
      image_label: "master"
      base_flavor: ${{ matrix.base_flavor }}
      targets: default
      push_images: false
    secrets: inherit
