name: Trigger builds on new commits to main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  get-comfyui-latest-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.fetch.outputs.release }}
    steps:
      - name: Get latest release
        id: fetch
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          owner: comfyanonymous
          repo: ComfyUI
          token: ${{ secrets.GITHUB_TOKEN }}

  build-base:
    concurrency:
      group: build-base
      cancel-in-progress: true
    uses: ./.github/workflows/build-docker.yml
    with:
      comfyui_ref: "master"
      bake_target: "base"
    permissions:
      contents: read
      packages: write
    secrets: inherit

  build-comfyui-master:
    needs: build-base
    concurrency:
      group: build-master
      cancel-in-progress: true
    uses: ./.github/workflows/build-docker.yml
    with:
      comfyui_ref: "master"
      image_label: "master"
    permissions:
      contents: read
      packages: write
    secrets: inherit

  build-comfyui-latest-release:
    needs: [get-comfyui-latest-release, build-base]
    concurrency:
      group: build-latest
      cancel-in-progress: true
    uses: ./.github/workflows/build-docker.yml
    with:
      comfyui_ref: "${{ needs.get-comfyui-latest-release.outputs.tag }}"
      image_label: "latest"
    permissions:
      contents: read
      packages: write
    secrets: inherit
