name: Trigger builds on new local commits

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  get-comfyui-latest-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.fetch.outputs.release }}
    steps:
      - name: Get latest release
        id: fetch
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          owner: comfyanonymous
          repo: ComfyUI
          token: ${{ secrets.GITHUB_TOKEN }}

  build-master:
    uses: ./.github/workflows/build-docker.yml
    with:
      comfyui_ref: "master"
      image_label: "master"
    secrets: inherit

  build-latest:
    needs: get-comfyui-latest-release
    uses: ./.github/workflows/build-docker.yml
    with:
      comfyui_ref: "${{ needs.get-comfyui-latest-release.outputs.tag }}"
      image_label: "latest"
    secrets: inherit
